spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  file:
    name: C:/InterviewAssignment/application.log
  logback:
    rollingpolicy:
      max-file-size: 10KB
  level:
    root: INFO